package jagex.osrs;

public class InboundPacketDescriptor {

    public static final InboundPacketDescriptor field2178;
    public static final InboundPacketDescriptor field2159;
    public static final InboundPacketDescriptor field2119;
    public static final InboundPacketDescriptor field2187;
    public static final InboundPacketDescriptor field2121;
    public static final InboundPacketDescriptor field2122;
    public static final InboundPacketDescriptor field2123;
    public static final InboundPacketDescriptor field2199;
    public static final InboundPacketDescriptor field2125;
    public static final InboundPacketDescriptor field2126;
    public static final InboundPacketDescriptor field2127;
    public static final InboundPacketDescriptor field2128;
    public static final InboundPacketDescriptor field2129;
    public static final InboundPacketDescriptor field2130;
    public static final InboundPacketDescriptor field2118;
    public static final InboundPacketDescriptor field2177;
    public static final InboundPacketDescriptor field2132;
    public static final InboundPacketDescriptor field2133;
    public static final InboundPacketDescriptor field2188;
    public static final InboundPacketDescriptor field2134;
    public static final InboundPacketDescriptor field2169;
    public static final InboundPacketDescriptor field2196;
    public static final InboundPacketDescriptor field2136;
    public static final InboundPacketDescriptor field2148;
    public static final InboundPacketDescriptor field2124;
    public static final InboundPacketDescriptor field2165;
    public static final InboundPacketDescriptor field2139;
    public static final InboundPacketDescriptor field2145;
    public static final InboundPacketDescriptor field2140;
    public static final InboundPacketDescriptor field2182;
    public static final InboundPacketDescriptor field2141;
    public static final InboundPacketDescriptor field2198;
    public static final InboundPacketDescriptor field2143;
    public static final InboundPacketDescriptor field2181;
    public static final InboundPacketDescriptor field2201;
    public static final InboundPacketDescriptor field2146;
    public static final InboundPacketDescriptor field2164;
    public static final InboundPacketDescriptor field2147;
    public static final InboundPacketDescriptor field2161;
    public static final InboundPacketDescriptor field2149;
    public static final InboundPacketDescriptor field2172;
    public static final InboundPacketDescriptor field2175;
    public static final InboundPacketDescriptor field2144;
    public static final InboundPacketDescriptor field2163;
    public static final InboundPacketDescriptor field2152;
    public static final InboundPacketDescriptor field2153;
    public static final InboundPacketDescriptor field2174;
    public static final InboundPacketDescriptor field2200;
    public static final InboundPacketDescriptor field2155;
    public static final InboundPacketDescriptor field2157;
    public static final InboundPacketDescriptor field2205;
    public static final InboundPacketDescriptor field2176;
    public static final InboundPacketDescriptor field2158;
    public static final InboundPacketDescriptor field2131;
    public static final InboundPacketDescriptor field2203;
    public static final InboundPacketDescriptor field2156;
    public static final InboundPacketDescriptor field2162;
    public static final InboundPacketDescriptor field2190;
    public static final InboundPacketDescriptor field2170;
    public static final InboundPacketDescriptor field2195;
    public static final InboundPacketDescriptor field2138;
    public static final InboundPacketDescriptor field2194;
    public static final InboundPacketDescriptor field2167;
    public static final InboundPacketDescriptor field2168;
    public static final InboundPacketDescriptor field2192;
    public static final InboundPacketDescriptor field2171;
    public static final InboundPacketDescriptor field2160;
    public static final InboundPacketDescriptor field2173;
    public static final InboundPacketDescriptor field2193;
    public static final InboundPacketDescriptor field2142;
    public static final InboundPacketDescriptor field2179;
    public static final InboundPacketDescriptor field2184;
    public static final InboundPacketDescriptor field2180;
    public static final InboundPacketDescriptor field2183;
    public static final InboundPacketDescriptor field2185;
    public static final InboundPacketDescriptor field2186;
    public static final InboundPacketDescriptor field2189;
    public static final InboundPacketDescriptor field2154;
    public static final InboundPacketDescriptor field2191;
    public static final InboundPacketDescriptor field2120;
    public static final InboundPacketDescriptor field2166;
    public static final InboundPacketDescriptor field2137;
    public static final InboundPacketDescriptor field2197;
    public static final InboundPacketDescriptor field2135;
    public static final InboundPacketDescriptor field2204;
    public static class68 field2150;
    static class251 index6;
    static int field2206;

    static {
        field2178 = new InboundPacketDescriptor(0, -2);
        field2159 = new InboundPacketDescriptor(1, 0);
        field2119 = new InboundPacketDescriptor(2, 0);
        field2187 = new InboundPacketDescriptor(3, -1);
        field2121 = new InboundPacketDescriptor(4, 6);
        field2122 = new InboundPacketDescriptor(5, 4);
        field2123 = new InboundPacketDescriptor(6, 4);
        field2199 = new InboundPacketDescriptor(7, 4);
        field2125 = new InboundPacketDescriptor(8, 6);
        field2126 = new InboundPacketDescriptor(9, 4);
        field2127 = new InboundPacketDescriptor(10, -2);
        field2128 = new InboundPacketDescriptor(11, 15);
        field2129 = new InboundPacketDescriptor(12, 5);
        field2130 = new InboundPacketDescriptor(13, 2);
        field2118 = new InboundPacketDescriptor(14, 3);
        field2132 = new InboundPacketDescriptor(15, 7);
        field2133 = new InboundPacketDescriptor(16, 1);
        field2134 = new InboundPacketDescriptor(17, -2);
        field2169 = new InboundPacketDescriptor(18, -2);
        field2136 = new InboundPacketDescriptor(19, -2);
        field2124 = new InboundPacketDescriptor(20, 10);
        field2165 = new InboundPacketDescriptor(21, 5);
        field2139 = new InboundPacketDescriptor(22, 6);
        field2140 = new InboundPacketDescriptor(23, 2);
        field2141 = new InboundPacketDescriptor(24, 6);
        field2198 = new InboundPacketDescriptor(25, 2);
        field2143 = new InboundPacketDescriptor(26, 5);
        field2181 = new InboundPacketDescriptor(27, -2);
        field2145 = new InboundPacketDescriptor(28, 0);
        field2146 = new InboundPacketDescriptor(29, 0);
        field2147 = new InboundPacketDescriptor(30, 4);
        field2148 = new InboundPacketDescriptor(31, 6);
        field2149 = new InboundPacketDescriptor(32, -2);
        field2175 = new InboundPacketDescriptor(33, -2);
        field2144 = new InboundPacketDescriptor(34, 1);
        field2152 = new InboundPacketDescriptor(35, 6);
        field2153 = new InboundPacketDescriptor(36, 6);
        field2200 = new InboundPacketDescriptor(37, -1);
        field2155 = new InboundPacketDescriptor(38, -2);
        field2205 = new InboundPacketDescriptor(39, 4);
        field2157 = new InboundPacketDescriptor(40, 5);
        field2158 = new InboundPacketDescriptor(41, 8);
        field2203 = new InboundPacketDescriptor(42, 14);
        field2156 = new InboundPacketDescriptor(43, -2);
        field2161 = new InboundPacketDescriptor(44, -2);
        field2162 = new InboundPacketDescriptor(45, -1);
        field2163 = new InboundPacketDescriptor(46, 2);
        field2164 = new InboundPacketDescriptor(47, -1);
        field2195 = new InboundPacketDescriptor(48, 12);
        field2194 = new InboundPacketDescriptor(49, 4);
        field2167 = new InboundPacketDescriptor(50, 10);
        field2168 = new InboundPacketDescriptor(51, -2);
        field2190 = new InboundPacketDescriptor(52, 0);
        field2170 = new InboundPacketDescriptor(53, -2);
        field2171 = new InboundPacketDescriptor(54, -1);
        field2160 = new InboundPacketDescriptor(55, 20);
        field2173 = new InboundPacketDescriptor(56, -2);
        field2174 = new InboundPacketDescriptor(57, 28);
        field2193 = new InboundPacketDescriptor(58, -2);
        field2176 = new InboundPacketDescriptor(59, 8);
        field2177 = new InboundPacketDescriptor(60, 1);
        field2138 = new InboundPacketDescriptor(61, 6);
        field2179 = new InboundPacketDescriptor(62, -2);
        field2180 = new InboundPacketDescriptor(63, 3);
        field2172 = new InboundPacketDescriptor(64, 2);
        field2182 = new InboundPacketDescriptor(65, 5);
        field2183 = new InboundPacketDescriptor(66, -1);
        field2184 = new InboundPacketDescriptor(67, 2);
        field2185 = new InboundPacketDescriptor(68, 1);
        field2186 = new InboundPacketDescriptor(69, 8);
        field2196 = new InboundPacketDescriptor(70, -2);
        field2188 = new InboundPacketDescriptor(71, 2);
        field2189 = new InboundPacketDescriptor(72, 2);
        field2154 = new InboundPacketDescriptor(73, 0);
        field2191 = new InboundPacketDescriptor(74, 1);
        field2192 = new InboundPacketDescriptor(75, 6);
        field2120 = new InboundPacketDescriptor(76, 6);
        field2137 = new InboundPacketDescriptor(77, 7);
        field2131 = new InboundPacketDescriptor(78, 0);
        field2201 = new InboundPacketDescriptor(79, -2);
        field2197 = new InboundPacketDescriptor(80, 2);
        field2135 = new InboundPacketDescriptor(81, -2);
        field2142 = new InboundPacketDescriptor(82, 8);
        field2166 = new InboundPacketDescriptor(83, 6);
        field2204 = new InboundPacketDescriptor(84, 2);
    }

    public final int field2202;
    public final int length;

    InboundPacketDescriptor(int var1, int var2) {
        this.field2202 = var1;
        this.length = var2;
    }

    public static boolean method3653(int var0, int var1) {
        return (var0 >> 29 & 1) != 0;
    }
}
