package jagex.osrs;

public class InboundPacketDescriptor {

    public static final InboundPacketDescriptor REBUILD_SCENE;
    public static final InboundPacketDescriptor LOGOUT;
    public static final InboundPacketDescriptor INBOUND_PACKET_2;
    public static final InboundPacketDescriptor INBOUND_PACKET_3;
    public static final InboundPacketDescriptor INBOUND_PACKET_4;
    public static final InboundPacketDescriptor INBOUND_PACKET_5;
    public static final InboundPacketDescriptor INBOUND_PACKET_6;
    public static final InboundPacketDescriptor INBOUND_PACKET_7;
    public static final InboundPacketDescriptor INBOUND_PACKET_8;
    public static final InboundPacketDescriptor INBOUND_PACKET_9;
    public static final InboundPacketDescriptor INBOUND_PACKET_10;
    public static final InboundPacketDescriptor INBOUND_PACKET_11;
    public static final InboundPacketDescriptor INBOUND_PACKET_12;
    public static final InboundPacketDescriptor INBOUND_PACKET_13;
    public static final InboundPacketDescriptor REMOVE_ITEM_STACK;
    public static final InboundPacketDescriptor INBOUND_PACKET_60;
    public static final InboundPacketDescriptor UPDATE_ITEM_STACK;
    public static final InboundPacketDescriptor INBOUND_PACKET_16;
    public static final InboundPacketDescriptor INBOUND_PACKET_71;
    public static final InboundPacketDescriptor INBOUND_PACKET_17;
    public static final InboundPacketDescriptor OPEN_URL;
    public static final InboundPacketDescriptor INBOUND_PACKET_70;
    public static final InboundPacketDescriptor INBOUND_PACKET_19;
    public static final InboundPacketDescriptor INBOUND_PACKET_31;
    public static final InboundPacketDescriptor INBOUND_PACKET_20;
    public static final InboundPacketDescriptor INBOUND_PACKET_21;
    public static final InboundPacketDescriptor INBOUND_PACKET_22;
    public static final InboundPacketDescriptor INBOUND_PACKET_28;
    public static final InboundPacketDescriptor INBOUND_PACKET_23;
    public static final InboundPacketDescriptor INBOUND_PACKET_65;
    public static final InboundPacketDescriptor INBOUND_PACKET_24;
    public static final InboundPacketDescriptor INBOUND_PACKET_25;
    public static final InboundPacketDescriptor CREATE_GROUND_ITEM;
    public static final InboundPacketDescriptor INBOUND_PACKET_27;
    public static final InboundPacketDescriptor INBOUND_PACKET_79;
    public static final InboundPacketDescriptor INBOUND_PACKET_29;
    public static final InboundPacketDescriptor INBOUND_PACKET_47;
    public static final InboundPacketDescriptor INBOUND_PACKET_30;
    public static final InboundPacketDescriptor INBOUND_PACKET_44;
    public static final InboundPacketDescriptor INBOUND_PACKET_32;
    public static final InboundPacketDescriptor INBOUNC_PACKET_64;
    public static final InboundPacketDescriptor INBOUND_PACKET_33;
    public static final InboundPacketDescriptor INBOUND_PACKET_34;
    public static final InboundPacketDescriptor INBOUND_PACKET_46;
    public static final InboundPacketDescriptor INBOUND_PACKET_35;
    public static final InboundPacketDescriptor INBOUND_PACKET_36;
    public static final InboundPacketDescriptor INBOUND_PACKET_57;
    public static final InboundPacketDescriptor INBOUND_PACKET_37;
    public static final InboundPacketDescriptor INBOUND_PACKET_38;
    public static final InboundPacketDescriptor INBOUND_PACKET_40;
    public static final InboundPacketDescriptor INBOUND_PACKET_39;
    public static final InboundPacketDescriptor INBOUND_PACKET_59;
    public static final InboundPacketDescriptor INBOUND_PACKET_41;
    public static final InboundPacketDescriptor INBOUND_PACKET_78;
    public static final InboundPacketDescriptor INBOUND_PACKET_42;
    public static final InboundPacketDescriptor INBOUND_PACKET_43;
    public static final InboundPacketDescriptor INBOUND_PACKET_45;
    public static final InboundPacketDescriptor INBOUND_PACKET_52;
    public static final InboundPacketDescriptor INBOUND_PACKET_53;
    public static final InboundPacketDescriptor INBOUND_PACKET_48;
    public static final InboundPacketDescriptor INBOUND_PACKET_61;
    public static final InboundPacketDescriptor INBOUND_PACKET_49;
    public static final InboundPacketDescriptor INBOUND_PACKET_50;
    public static final InboundPacketDescriptor REBUILD_INSTANCED_SCENE;
    public static final InboundPacketDescriptor INBOUND_PACKET_75;
    public static final InboundPacketDescriptor INBOUND_PACKET_54;
    public static final InboundPacketDescriptor INBOUND_PACKET_55;
    public static final InboundPacketDescriptor INBOUND_PACKET_56;
    public static final InboundPacketDescriptor INBOUND_PACKET_58;
    public static final InboundPacketDescriptor INBOUND_PACKET_82;
    public static final InboundPacketDescriptor EXECUTE_SCRIPT;
    public static final InboundPacketDescriptor INBOUND_PACKET_67;
    public static final InboundPacketDescriptor INBOUND_PACKET_63;
    public static final InboundPacketDescriptor SET_PLAYER_OPTION;
    public static final InboundPacketDescriptor INBOUND_PACKET_68;
    public static final InboundPacketDescriptor INBOUND_PACKET_69;
    public static final InboundPacketDescriptor INBOUND_PACKET_72;
    public static final InboundPacketDescriptor INBOUND_PACKET_73;
    public static final InboundPacketDescriptor INBOUND_PACKET_74;
    public static final InboundPacketDescriptor INBOUND_PACKET_76;
    public static final InboundPacketDescriptor INBOUND_PACKET_83;
    public static final InboundPacketDescriptor INBOUND_PACKET_77;
    public static final InboundPacketDescriptor INBOUND_PACKET_80;
    public static final InboundPacketDescriptor INBOUND_PACKET_81;
    public static final InboundPacketDescriptor INBOUND_PACKET_84;
    public static class68 field2150;
    static class251 index6;
    static int field2206;

    static {
        REBUILD_SCENE = new InboundPacketDescriptor(0, -2);
        LOGOUT = new InboundPacketDescriptor(1, 0);
        INBOUND_PACKET_2 = new InboundPacketDescriptor(2, 0);
        INBOUND_PACKET_3 = new InboundPacketDescriptor(3, -1);
        INBOUND_PACKET_4 = new InboundPacketDescriptor(4, 6);
        INBOUND_PACKET_5 = new InboundPacketDescriptor(5, 4);
        INBOUND_PACKET_6 = new InboundPacketDescriptor(6, 4);
        INBOUND_PACKET_7 = new InboundPacketDescriptor(7, 4);
        INBOUND_PACKET_8 = new InboundPacketDescriptor(8, 6);
        INBOUND_PACKET_9 = new InboundPacketDescriptor(9, 4);
        INBOUND_PACKET_10 = new InboundPacketDescriptor(10, -2);
        INBOUND_PACKET_11 = new InboundPacketDescriptor(11, 15);
        INBOUND_PACKET_12 = new InboundPacketDescriptor(12, 5);
        INBOUND_PACKET_13 = new InboundPacketDescriptor(13, 2);
        REMOVE_ITEM_STACK = new InboundPacketDescriptor(14, 3);
        UPDATE_ITEM_STACK = new InboundPacketDescriptor(15, 7);
        INBOUND_PACKET_16 = new InboundPacketDescriptor(16, 1);
        INBOUND_PACKET_17 = new InboundPacketDescriptor(17, -2);
        OPEN_URL = new InboundPacketDescriptor(18, -2);
        INBOUND_PACKET_19 = new InboundPacketDescriptor(19, -2);
        INBOUND_PACKET_20 = new InboundPacketDescriptor(20, 10);
        INBOUND_PACKET_21 = new InboundPacketDescriptor(21, 5);
        INBOUND_PACKET_22 = new InboundPacketDescriptor(22, 6);
        INBOUND_PACKET_23 = new InboundPacketDescriptor(23, 2);
        INBOUND_PACKET_24 = new InboundPacketDescriptor(24, 6);
        INBOUND_PACKET_25 = new InboundPacketDescriptor(25, 2);
        CREATE_GROUND_ITEM = new InboundPacketDescriptor(26, 5);
        INBOUND_PACKET_27 = new InboundPacketDescriptor(27, -2);
        INBOUND_PACKET_28 = new InboundPacketDescriptor(28, 0);
        INBOUND_PACKET_29 = new InboundPacketDescriptor(29, 0);
        INBOUND_PACKET_30 = new InboundPacketDescriptor(30, 4);
        INBOUND_PACKET_31 = new InboundPacketDescriptor(31, 6);
        INBOUND_PACKET_32 = new InboundPacketDescriptor(32, -2);
        INBOUND_PACKET_33 = new InboundPacketDescriptor(33, -2);
        INBOUND_PACKET_34 = new InboundPacketDescriptor(34, 1);
        INBOUND_PACKET_35 = new InboundPacketDescriptor(35, 6);
        INBOUND_PACKET_36 = new InboundPacketDescriptor(36, 6);
        INBOUND_PACKET_37 = new InboundPacketDescriptor(37, -1);
        INBOUND_PACKET_38 = new InboundPacketDescriptor(38, -2);
        INBOUND_PACKET_39 = new InboundPacketDescriptor(39, 4);
        INBOUND_PACKET_40 = new InboundPacketDescriptor(40, 5);
        INBOUND_PACKET_41 = new InboundPacketDescriptor(41, 8);
        INBOUND_PACKET_42 = new InboundPacketDescriptor(42, 14);
        INBOUND_PACKET_43 = new InboundPacketDescriptor(43, -2);
        INBOUND_PACKET_44 = new InboundPacketDescriptor(44, -2);
        INBOUND_PACKET_45 = new InboundPacketDescriptor(45, -1);
        INBOUND_PACKET_46 = new InboundPacketDescriptor(46, 2);
        INBOUND_PACKET_47 = new InboundPacketDescriptor(47, -1);
        INBOUND_PACKET_48 = new InboundPacketDescriptor(48, 12);
        INBOUND_PACKET_49 = new InboundPacketDescriptor(49, 4);
        INBOUND_PACKET_50 = new InboundPacketDescriptor(50, 10);
        REBUILD_INSTANCED_SCENE = new InboundPacketDescriptor(51, -2);
        INBOUND_PACKET_52 = new InboundPacketDescriptor(52, 0);
        INBOUND_PACKET_53 = new InboundPacketDescriptor(53, -2);
        INBOUND_PACKET_54 = new InboundPacketDescriptor(54, -1);
        INBOUND_PACKET_55 = new InboundPacketDescriptor(55, 20);
        INBOUND_PACKET_56 = new InboundPacketDescriptor(56, -2);
        INBOUND_PACKET_57 = new InboundPacketDescriptor(57, 28);
        INBOUND_PACKET_58 = new InboundPacketDescriptor(58, -2);
        INBOUND_PACKET_59 = new InboundPacketDescriptor(59, 8);
        INBOUND_PACKET_60 = new InboundPacketDescriptor(60, 1);
        INBOUND_PACKET_61 = new InboundPacketDescriptor(61, 6);
        EXECUTE_SCRIPT = new InboundPacketDescriptor(62, -2);
        INBOUND_PACKET_63 = new InboundPacketDescriptor(63, 3);
        INBOUNC_PACKET_64 = new InboundPacketDescriptor(64, 2);
        INBOUND_PACKET_65 = new InboundPacketDescriptor(65, 5);
        SET_PLAYER_OPTION = new InboundPacketDescriptor(66, -1);
        INBOUND_PACKET_67 = new InboundPacketDescriptor(67, 2);
        INBOUND_PACKET_68 = new InboundPacketDescriptor(68, 1);
        INBOUND_PACKET_69 = new InboundPacketDescriptor(69, 8);
        INBOUND_PACKET_70 = new InboundPacketDescriptor(70, -2);
        INBOUND_PACKET_71 = new InboundPacketDescriptor(71, 2);
        INBOUND_PACKET_72 = new InboundPacketDescriptor(72, 2);
        INBOUND_PACKET_73 = new InboundPacketDescriptor(73, 0);
        INBOUND_PACKET_74 = new InboundPacketDescriptor(74, 1);
        INBOUND_PACKET_75 = new InboundPacketDescriptor(75, 6);
        INBOUND_PACKET_76 = new InboundPacketDescriptor(76, 6);
        INBOUND_PACKET_77 = new InboundPacketDescriptor(77, 7);
        INBOUND_PACKET_78 = new InboundPacketDescriptor(78, 0);
        INBOUND_PACKET_79 = new InboundPacketDescriptor(79, -2);
        INBOUND_PACKET_80 = new InboundPacketDescriptor(80, 2);
        INBOUND_PACKET_81 = new InboundPacketDescriptor(81, -2);
        INBOUND_PACKET_82 = new InboundPacketDescriptor(82, 8);
        INBOUND_PACKET_83 = new InboundPacketDescriptor(83, 6);
        INBOUND_PACKET_84 = new InboundPacketDescriptor(84, 2);
    }

    public final int field2202;
    public final int length;

    InboundPacketDescriptor(int var1, int var2) {
        this.field2202 = var1;
        this.length = var2;
    }

    public static boolean method3653(int var0, int var1) {
        return (var0 >> 29 & 1) != 0;
    }
}
